@ <term> ::=
    | <universe>                            -- Universes
    | <var>                                 -- vars
    | "pi" <var> ":" <term> "." <term>      -- Dependent function type (Π)
    | "lambda" <var> "." <term>             -- Lambda abstraction
    | <term> <term>                         -- Application
    | "sigma" <var> ":" <term> "." <term>   -- Dependent pair type (Σ)
    | "("<term> "," <term>")"               -- Pair constructor
    | "let" "("<var> "," <var>")" "=" <term> "in" <term>  -- Σ-elimination (pattern matching)
    | <term> "+" <term>                     -- Coproduct type (A + B)
    | "inl" <term> | "inr" <term>           -- Injections into coproduct
    | "case" <term> "of" "inl" <var> "to" <term> -- Coproduct elimination left
    | "case" <term> "of" "inr" <var> "to" <term> -- Coproduct elimination right
    | "unit_type"                           -- Unit type (canonical element: ⋆)
    | "star"                                -- Inhabitant of the unit type
    | "empty_type"                          -- Empty type
    | "absurd" <term>                       -- Elimination for the empty type (ex falso quodlibet)
    | "Id_" <term> "("<term>"," <term>")"   -- Identity type (Id_A(x, y))
    | "refl_" <term> <term>                 -- Reflexivity (refl_A x : Id_A(x, x))
    | "J" "["<var> ":" <term>"]" "["<var> ":" <term>"]" "["<var> ":" "Id("<var>","<var>")]" "." "("<term>")" 'to' <term>  -- Path induction (J rule)

@ <universe> ::= "Type_" <number>             -- Hierarchy of universes
@ <var> ::= "var_" <name> <number>            -- variable names

@ <number> ::= <digit> 
    | <number> <digit>

@ <digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
@ <name> ::= /[a-zA-Z_]+/